In [1]:
# Импортирование неодходимых библиотек 
import numpy as np
from scipy.linalg import logm, expm, sqrtm
from numpy import linalg as LA

In [2]:
# Импортирование библиотек для иницализации основных параметров системы
from calc_tools import Fazy, System, Garmoniki, Rachety

In [3]:
# Задание значении характеристик материала для фаз и троса
Faza_A = Fazy("Фаза А", 35.336, 1.0, 240.0, 0.0, 19.0)
Faza_B = Fazy("Фаза В", 35.336, 1.0, 240.0, 6.3, 19.0)
Faza_C = Fazy("Фаза С", 35.336, 1.0, 240.0, 4.2, 25.0)
Tross = Fazy("Тросс", 17.336, 8.0, 50.0, 2.1, 28.0)

In [4]:
# В данном случае у нас будет 50 гармоник от [1 до 50]
garmoniki = Garmoniki(50)

In [5]:
# Создание объекта для проведения расчетов
rashet = Rachety()

In [6]:
# Вычисление погонных активных сопротивлении для фаз и троса.
# Получаем матрицу с размерностью [4 на 50]
pogon_aktiv_soprotiv_faz = rashet.pogon_aktiv_soprotiv(Fazy, garmoniki)

In [7]:
# Смотрим...
pogon_aktiv_soprotiv_faz

array([[0.14432738, 0.15984166, 0.17285428, 0.18446906, 0.19514405,
        0.2051253 , 0.21456429, 0.22356262, 0.23219262, 0.15657597,
        0.16277943, 0.16870677, 0.17439186, 0.17986218, 0.18514039,
        0.19024539, 0.19519321, 0.19999751, 0.20467012, 0.2092213 ,
        0.21366005, 0.21799432, 0.22223115, 0.22637683, 0.23043701,
        0.23441677, 0.2383207 , 0.24215297, 0.24591741, 0.24961748,
        0.25325638, 0.25683705, 0.26036219, 0.26383432, 0.26725574,
        0.27062863, 0.27395499, 0.2772367 , 0.2804755 , 0.28367304,
        0.28683085, 0.28995038, 0.29303299, 0.29607996, 0.2990925 ,
        0.30207174, 0.30501878, 0.30793462, 0.31082025, 0.31367658],
       [0.14432738, 0.15984166, 0.17285428, 0.18446906, 0.19514405,
        0.2051253 , 0.21456429, 0.22356262, 0.23219262, 0.15657597,
        0.16277943, 0.16870677, 0.17439186, 0.17986218, 0.18514039,
        0.19024539, 0.19519321, 0.19999751, 0.20467012, 0.2092213 ,
        0.21366005, 0.21799432, 0.22223115, 0.2

In [8]:
# Вычисление погонных индуктивных сопротивлении для фаз и троса.
# Получаем матрицу с размерностью [4 х 4 х 50]
inductiv_soprotiv_faz = rashet.inductiv_soprotiv(Fazy, garmoniki)

In [9]:
# Смотрим...
inductiv_soprotiv_faz[0]

array([[230.42892558, 100.24684566,  97.26749865,  92.66618175],
       [100.24684566, 230.42892558, 100.06901204,  91.24163763],
       [ 97.26749865, 100.06901204, 230.42892558, 110.98034618],
       [ 92.66618175,  91.24163763, 110.98034618, 245.94524846]])

In [10]:
# Вычисление погонных ёмкостных проводимостей для фаз и троса.
# Получаем матрицу с размерностью [4 х 4 х 50]
emkostn_provodimost_faz = rashet.emkostnaya_provodimost(Fazy, garmoniki)

In [11]:
# Смотрим...
emkostn_provodimost_faz[0]

array([[2.08572308e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.08572308e-06, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.01956370e-06, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.82972738e-06]])

In [12]:
# Матрица полных погонных прводимостей
Y = rashet.polnaya_provodimost(emkostn_provodimost_faz)

In [13]:
# Смотрим
Y[0]
    

array([[0.+2.08572308e-06j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+2.08572308e-06j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+2.01956370e-06j,
        0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+1.82972738e-06j]])

In [14]:
# Матрица полных погонных сопротивлении
Z = rashet.polnoe_soprotivlenye(inductiv_soprotiv_faz, pogon_aktiv_soprotiv_faz)

In [15]:
# Смотрим 
Z[1]

array([[0.15984166+460.85785116j, 0.        +200.49369132j,
        0.        +194.53499729j, 0.        +185.3323635j ],
       [0.        +200.49369132j, 0.15984166+460.85785116j,
        0.        +200.13802409j, 0.        +182.48327526j],
       [0.        +194.53499729j, 0.        +200.13802409j,
        0.15984166+460.85785116j, 0.        +221.96069236j],
       [0.        +185.3323635j , 0.        +182.48327526j,
        0.        +221.96069236j, 1.51235406+491.89049693j]])

In [16]:
# Функция для расчета комплексных квадратных матриц лямбда_напряж и лямбда_ток
lambda_U, lambda_I = rashet.calculate_lambdas(Z, Y)

In [17]:
# Проверка полученных данных
lambda_U.shape

(50, 4, 4)

In [18]:
# Функция для расчета комплексных квадратных матриц экспонен_напряжения и экспонента_ток
# Для примера были взяты значения для отрезка 300
pos_expon_U, neg_expon_U = rashet.calculate_exponentials(lambda_U, 300)
pos_expon_I, neg_expon_I = rashet.calculate_exponentials(lambda_I, 300)

In [19]:
# Проверка полученных данных
pos_expon_U.shape

(50, 4, 4)

In [20]:
######################################### TESTING POLYGON #############################################

In [21]:
inductiv_soprotiv_faz[0]

array([[1.09556478, 0.68118235, 0.6716988 , 0.65705235],
       [0.68118235, 1.09556478, 0.68061629, 0.65251788],
       [0.6716988 , 0.68061629, 1.09556478, 0.71534815],
       [0.65705235, 0.65251788, 0.71534815, 1.09556478]])

In [22]:
np.log10(1000/Faza_A.radius)*0.145*np.pi*100

230.4289255793728