In [1]:
# Импортирование неодходимых библиотек 
import numpy as np
from scipy.linalg import logm, expm, sqrtm
from numpy import linalg as LA

In [2]:
# Импортирование библиотек для иницализации основных параметров системы
from calc_tools import Fazy, System, Garmoniki, Rachety

In [3]:
# Задание значении характеристик материала для фаз и троса

Faza_A = Fazy("Фаза А", 35.336, 1.0, 240.0, 0.0, 19.0)
Faza_B = Fazy("Фаза В", 35.336, 1.0, 240.0, 6.3, 19.0)
Faza_C = Fazy("Фаза С", 35.336, 1.0, 240.0, 4.2, 25.0)
Tross = Fazy("Тросс", 17.336, 8.0, 240.0, 2.1, 28.0)

In [4]:
# В данном случае у нас будет 50 гармоник от [1 до 50]
garmoniki = Garmoniki(50)

In [5]:
# Создание объекта для проведения расчетов
rashet = Rachety()

In [6]:
# Вычисление погонных активных сопротивлении для фаз и троса.
# Получаем матрицу с размерностью [4 на 50]
pogon_aktiv_soprotiv_faz = rashet.pogon_aktiv_soprotiv(Fazy, garmoniki)

In [7]:
# Смотрим...
pogon_aktiv_soprotiv_faz

array([[0.14432738, 0.15984166, 0.17285428, 0.18446906, 0.19514405,
        0.2051253 , 0.21456429, 0.22356262, 0.23219262, 0.15657597,
        0.16277943, 0.16870677, 0.17439186, 0.17986218, 0.18514039,
        0.19024539, 0.19519321, 0.19999751, 0.20467012, 0.2092213 ,
        0.21366005, 0.21799432, 0.22223115, 0.22637683, 0.23043701,
        0.23441677, 0.2383207 , 0.24215297, 0.24591741, 0.24961748,
        0.25325638, 0.25683705, 0.26036219, 0.26383432, 0.26725574,
        0.27062863, 0.27395499, 0.2772367 , 0.2804755 , 0.28367304,
        0.28683085, 0.28995038, 0.29303299, 0.29607996, 0.2990925 ,
        0.30207174, 0.30501878, 0.30793462, 0.31082025, 0.31367658],
       [0.14432738, 0.15984166, 0.17285428, 0.18446906, 0.19514405,
        0.2051253 , 0.21456429, 0.22356262, 0.23219262, 0.15657597,
        0.16277943, 0.16870677, 0.17439186, 0.17986218, 0.18514039,
        0.19024539, 0.19519321, 0.19999751, 0.20467012, 0.2092213 ,
        0.21366005, 0.21799432, 0.22223115, 0.2

In [8]:
# Вычисление погонных индуктивных сопротивлении для фаз и троса.
# Получаем матрицу с размерностью [4 х 4 х 50]
inductiv_soprotiv_faz = rashet.inductiv_soprotiv(Fazy, garmoniki)

In [9]:
# Смотрим...
inductiv_soprotiv_faz

array([[[1.09556478, 0.68118235, 0.6716988 , 0.65705235],
        [0.68118235, 1.09556478, 0.68061629, 0.65251788],
        [0.6716988 , 0.68061629, 1.09556478, 0.71534815],
        [0.65705235, 0.65251788, 0.71534815, 1.09556478]],

       [[1.13921413, 0.7248317 , 0.71534815, 0.7007017 ],
        [0.7248317 , 1.13921413, 0.72426564, 0.69616723],
        [0.71534815, 0.72426564, 1.13921413, 0.75899749],
        [0.7007017 , 0.69616723, 0.75899749, 1.13921413]],

       [[1.16474736, 0.75036493, 0.74088138, 0.72623493],
        [0.75036493, 1.16474736, 0.74979887, 0.72170047],
        [0.74088138, 0.74979887, 1.16474736, 0.78453073],
        [0.72623493, 0.72170047, 0.78453073, 1.16474736]],

       [[1.18286348, 0.76848105, 0.75899749, 0.74435105],
        [0.76848105, 1.18286348, 0.76791499, 0.73981658],
        [0.75899749, 0.76791499, 1.18286348, 0.80264684],
        [0.74435105, 0.73981658, 0.80264684, 1.18286348]],

       [[1.19691543, 0.782533  , 0.77304945, 0.758403  ],
      

In [10]:
# Вычисление погонных ёмкостных проводимостей для фаз и троса.
# Получаем матрицу с размерностью [4 х 4 х 50]
emkostn_provodimost_faz = rashet.emkostnaya_provodimost(Fazy, garmoniki)

In [11]:
# Смотрим...
emkostn_provodimost_faz

array([[[2.08572308e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 2.08572308e-06, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 2.01956370e-06, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.99345183e-06]],

       [[4.17144615e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 4.17144615e-06, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 4.03912740e-06, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.98690366e-06]],

       [[6.25716923e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 6.25716923e-06, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 6.05869110e-06, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.98035550e-06]],

       [[8.34289230e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 8.34289

In [12]:
# Матрица полных погонных прводимостей
Y = rashet.polnaya_provodimost(emkostn_provodimost_faz)

In [13]:
# Смотрим
Y
    

array([[[0.+2.08572308e-06j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+2.08572308e-06j, 0.+0.00000000e+00j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+2.01956370e-06j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
         0.+1.99345183e-06j]],

       [[0.+4.17144615e-06j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+4.17144615e-06j, 0.+0.00000000e+00j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+4.03912740e-06j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
         0.+3.98690366e-06j]],

       [[0.+6.25716923e-06j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
         0.+0.00000000e+00j],
        [0.+0.00000000e+00j, 0.+6.25716923e-06j, 0.+0.00000000e+00j,
         0.+0.00000000e+00j],
      

In [14]:
# Матрица полных погонных сопротивлении
Z = rashet.polnoe_soprotivlenye(inductiv_soprotiv_faz, pogon_aktiv_soprotiv_faz)

In [15]:
# Смотрим 
Z

array([[[0.14432738+1.09556478j, 0.        +0.68118235j,
         0.        +0.6716988j , 0.        +0.65705235j],
        [0.        +0.68118235j, 0.14432738+1.09556478j,
         0.        +0.68061629j, 0.        +0.65251788j],
        [0.        +0.6716988j , 0.        +0.68061629j,
         0.14432738+1.09556478j, 0.        +0.71534815j],
        [0.        +0.65705235j, 0.        +0.65251788j,
         0.        +0.71534815j, 0.37429884+1.09556478j]],

       [[0.15984166+1.13921413j, 0.        +0.7248317j ,
         0.        +0.71534815j, 0.        +0.7007017j ],
        [0.        +0.7248317j , 0.15984166+1.13921413j,
         0.        +0.72426564j, 0.        +0.69616723j],
        [0.        +0.71534815j, 0.        +0.72426564j,
         0.15984166+1.13921413j, 0.        +0.75899749j],
        [0.        +0.7007017j , 0.        +0.69616723j,
         0.        +0.75899749j, 0.45298192+1.13921413j]],

       [[0.17285428+1.16474736j, 0.        +0.75036493j,
         0.        

In [16]:
                 # Расчет комплексных квадратных матриц лямбда_напряж и лямбда_ток

# Произведение матриц собственных и взаимных погонных сопротивлений и проводимостей
Au = np.matmul(Z, Y) 
Ai = np.matmul(Y, Z)

In [17]:
# Функция для расчета комплексных квадратных матриц лямбда_напряж и лямбда_ток

def calc_lambda(Mat):
    temp_array = list()
    for i in range(len(garmoniki)):
        lambda_i =  sqrtm(Mat[i])
        temp_array.append(lambda_i)
    lambda_U = np.array(temp_array)
    return lambda_U

In [18]:
# Вызов функции и произведение расчетов
lambda_U = calc_lambda(Au)
lambda_I = calc_lambda(Ai)

In [19]:
# Проверяем правильность вычисления комплексных матриц
# Считется, что если матрица А = вкорне(В) --> тогда, В*В = А

# Смотрим и сравниваем

In [20]:
np.matmul(lambda_I, lambda_I)[0]  # B*B

array([[-2.28504475e-06+3.01026939e-07j, -1.42075775e-06+3.04402465e-22j,
        -1.40097768e-06-6.48509600e-22j, -1.37042925e-06+4.16899029e-22j],
       [-1.42075775e-06-1.65436123e-23j, -2.28504475e-06+3.01026939e-07j,
        -1.41957710e-06+1.98523347e-23j, -1.36097161e-06-1.98523347e-23j],
       [-1.35653850e-06+3.27563523e-22j, -1.37454795e-06-9.52912066e-22j,
        -2.21256286e-06+2.91478330e-07j, -1.44469115e-06-6.61744490e-23j],
       [-1.30980221e-06-4.43368808e-22j, -1.30076297e-06-3.70576914e-22j,
        -1.42601207e-06-6.88214270e-22j, -2.18395562e-06+7.46146713e-07j]])

In [21]:
Ai[0]  # A

array([[-2.28504475e-06+3.01026939e-07j, -1.42075775e-06+0.00000000e+00j,
        -1.40097768e-06+0.00000000e+00j, -1.37042925e-06+0.00000000e+00j],
       [-1.42075775e-06+0.00000000e+00j, -2.28504475e-06+3.01026939e-07j,
        -1.41957710e-06+0.00000000e+00j, -1.36097161e-06+0.00000000e+00j],
       [-1.35653850e-06+0.00000000e+00j, -1.37454795e-06+0.00000000e+00j,
        -2.21256286e-06+2.91478330e-07j, -1.44469115e-06+0.00000000e+00j],
       [-1.30980221e-06+0.00000000e+00j, -1.30076297e-06+0.00000000e+00j,
        -1.42601207e-06+0.00000000e+00j, -2.18395562e-06+7.46146713e-07j]])

In [22]:
# Результаты практически одинаковые

In [23]:
# Функция для расчета комплексных квадратных матриц экспонен_напряжения и экспонента_ток

def calc_exponents(lambd, dlina):
    temp_array1 = list()
    temp_array2 = list()
    
    for i in range(len(garmoniki)):
        expm_i = np.dot(expm(lambd[i]), dlina)
        temp_array1.append(expm_i)
    
    for i in range(len(garmoniki)):
        expm_i = np.dot(expm(lambd[i]), -1*dlina)
        temp_array2.append(expm_i)
        
    pos_exponent = np.array(temp_array1)
    neg_exponent = np.array(temp_array2)
    
    return pos_exponent, neg_exponent

In [24]:
# Длина линии выбрана как 7км (пример)
pos_U_exponent, neg_U_exponent = calc_exponents(lambda_U, 7) 
pos_I_exponent, neg_I_exponent = calc_exponents(lambda_I, 7)

In [25]:
# Смотрим и проверяем
pos_U_exponent[0]

array([[ 7.00093883e+00+0.00950239j, -1.74598154e-04+0.00289426j,
        -1.40252175e-04+0.00271173j, -2.87048029e-04+0.00253963j],
       [-1.74598154e-04+0.00289426j,  7.00094008e+00+0.0094936j ,
        -1.51534207e-04+0.0027737j , -2.76729612e-04+0.00250466j],
       [-1.44846729e-04+0.00280056j, -1.56498353e-04+0.00286457j,
         7.00096883e+00+0.00924454j, -3.73651555e-04+0.00290771j],
       [-3.00334670e-04+0.00265718j, -2.89538642e-04+0.00262059j,
        -3.78545950e-04+0.0029458j ,  7.00218511e+00+0.00950225j]])

In [26]:
#       !!! Правильный вариант нахождение матриц "лямбда напряжения и тока" !!!
#             (через определитель Вандермонда и теорему Гамильтона-Кэли)

In [65]:
def calculate_lambdas(Z, Y): # <----!ВАЖНО! "Сначала Z, потом Y"
    
    # Проверка правильности входных матриц
    assert len(Z.shape) == len(Y.shape) and len(Z.shape) == 3, "Both Z and Y must be 3 dimentional matrices"
    for dim in range(len(Z.shape)):
        assert Z.shape[dim] == Y.shape[dim], "Z and Y must be equal in size"
    assert Z.shape[1] == Z.shape[2], "Z and Y must be sqare matrices"
    
    lambda_U_main_matrix = []
    lambda_I_main_matrix = []
    
    ###   Расчет матрицы лямбда напряжения !!!
    for harm in range(Z.shape[0]):
        list_of_matrices = []
        list_of_deters = []
        Au = np.dot(Z[harm], Y[harm])
        eigen_values = LA.eigvals(Au)
        sqared_eigen_values = np.sqrt(eigen_values)

        main_vander_matrix = np.vander(eigen_values, increasing=True)
        main_deter_vander = LA.det(main_vander_matrix)

        for i in range(main_vander_matrix.shape[0]):
            vander_matrix_n = np.vander(eigen_values, increasing=True)

            vander_matrix_n[:,i] = sqared_eigen_values
            matrix_deter_n = LA.det(vander_matrix_n)

            list_of_matrices.append(vander_matrix_n)
            list_of_deters.append(matrix_deter_n)

        sample = np.zeros(main_vander_matrix.shape, main_vander_matrix.dtype)
        for i in range(main_vander_matrix.shape[0]):
            term = ((Au**i)*(list_of_deters[i]/main_deter_vander)) # Needs to be checked! 
            sample += term

        lambda_U_main_matrix.append(sample)

    ###   Расчет матрицы лямбда тока !!!      
    for harm in range(Z.shape[0]):
        list_of_matrices = []
        list_of_deters = []
        Ai = np.dot(Y[harm], Z[harm])
        eigen_values = LA.eigvals(Ai)
        sqared_eigen_values = np.sqrt(eigen_values)

        main_vander_matrix = np.vander(eigen_values, increasing=True)
        main_deter_vander = LA.det(main_vander_matrix)

        for i in range(main_vander_matrix.shape[0]):
            vander_matrix_n = np.vander(eigen_values, increasing=True)

            vander_matrix_n[:,i] = sqared_eigen_values
            matrix_deter_n = LA.det(vander_matrix_n)

            list_of_matrices.append(vander_matrix_n)
            list_of_deters.append(matrix_deter_n)

        sample = np.zeros(main_vander_matrix.shape, main_vander_matrix.dtype)
        for i in range(main_vander_matrix.shape[0]):
            term = ((Ai**i)*(list_of_deters[i]/main_deter_vander)) # Needs to be checked! 
            sample += term

        lambda_I_main_matrix.append(sample)

    # Возвращает 2 матрицы размерностью [50x4x4] каждая для лямбды 1)напряжения и лямбды 2)тока соответственно
    return np.array(lambda_U_main_matrix), np.array(lambda_I_main_matrix) 

In [66]:
lambda_U, lambda_I = calculate_lambdas(Z, Y)

In [79]:
def calculate_U_exponentials(lambda_UI, x):
    assert len(lambda_UI.shape) == 3, "Lambda matrix must be 3 dimentional matrix"
    assert lambda_UI.shape[1] == lambda_UI.shape[2], "Lambda matrix must square matrix"
    assert type(x) in [int, float], "Distance x must be either int or float type"
    
    positive_expon_matrix = []
    negative_expon_matrix = []
    
    for harm in range(lambda_UI.shape[0]):
        list_of_matrices = []
        list_of_deters = []
        
        Aui = np.dot(lambda_UI[harm], x)
        eigen_values = LA.eigvals(Aui)
        expon_eigen_values = np.exp(eigen_values)
        
        main_vander_matrix = np.vander(eigen_values, increasing=True)
        main_deter_vander = LA.det(main_vander_matrix)
        
        for i in range(main_vander_matrix.shape[0]):
            vander_matrix_n = np.vander(eigen_values, increasing=True)

            vander_matrix_n[:,i] = expon_eigen_values
            matrix_deter_n = LA.det(vander_matrix_n)

            list_of_matrices.append(vander_matrix_n)
            list_of_deters.append(matrix_deter_n)

        sample = np.zeros(main_vander_matrix.shape, main_vander_matrix.dtype)
        for i in range(main_vander_matrix.shape[0]):
            term = ((Aui**i)*(list_of_deters[i]/main_deter_vander)) # Needs to be checked! 
            sample += term

        positive_expon_matrix.append(sample)


        
    for harm in range(lambda_UI.shape[0]):
        list_of_matrices = []
        list_of_deters = []
        
        Aui = np.dot(lambda_UI[harm], -1*x)
        eigen_values = LA.eigvals(Aui)
        expon_eigen_values = np.exp(eigen_values)
        
        main_vander_matrix = np.vander(eigen_values, increasing=True)
        main_deter_vander = LA.det(main_vander_matrix)
        
        for i in range(main_vander_matrix.shape[0]):
            vander_matrix_n = np.vander(eigen_values, increasing=True)

            vander_matrix_n[:,i] = expon_eigen_values
            matrix_deter_n = LA.det(vander_matrix_n)

            list_of_matrices.append(vander_matrix_n)
            list_of_deters.append(matrix_deter_n)

        sample = np.zeros(main_vander_matrix.shape, main_vander_matrix.dtype)
        for i in range(main_vander_matrix.shape[0]):
            term = ((Aui**i)*(list_of_deters[i]/main_deter_vander)) # Needs to be checked! 
            sample += term

        negative_expon_matrix.append(sample)
    
    # Возвращает 2 матрицы размерностью [50x4x4] каждая для +/- экспоненциальной для определенной длины "х" 
    return np.array(positive_expon_matrix), np.array(negative_expon_matrix)

In [82]:
ep, en = calculate_U_exponentials(lambda_U, 300)